"""ETL Stage 1 — parse an X list export and upsert candidates.

Two input formats supported:

1. **JSON** — preferred. An array of records ``{handle, display_name?, bio?, followers?}``.
   Generated by a userscript or a browser-console scrape over the rendered list page.

2. **HTML** — fallback. A saved-as-html copy of ``x.com/i/lists/{id}/members``.
   We extract any anchor whose href looks like a user-profile link (``/handle`` with
   no further path segments and not a known route name like ``home``, ``i``, etc.).
   Display name is read from the anchor's text or a nearby span; bio/followers are
   not reliably present in the static HTML and stay NULL for HTML-sourced rows.

The parser is intentionally permissive — bad rows are dropped at parse time, not
upsert time, so we can re-run safely. ``run_ingest()`` is idempotent: re-running
on the same export appends ``discovery_source`` once and bumps ``last_seen_at``.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from sable_kol.db import normalize_handle, open_db, upsert_candidate


# Routes that look like ``/handle`` but are not user profiles. We drop these
# when parsing HTML.
_HTML_ROUTE_DENYLIST = {
    "home", "explore", "notifications", "messages", "i", "search", "compose",
    "settings", "tos", "privacy", "rules", "login", "signup", "verified-orgs-signup",
    "logout", "search-advanced", "intent", "share", "about", "help",
    "tweet", "tweets", "status", "lists", "communities", "topics", "moments",
    "hashtag", "bookmarks", "jobs",
}

# Match a single-segment path that *could* be a handle. Twitter handles are
# 1–15 chars, ASCII letters/digits/underscore.
_HANDLE_PATH_RE = re.compile(r"^/([A-Za-z0-9_]{1,15})/?$")


@dataclass
class ParsedCandidate:
    handle: str
    display_name: str | None = None
    bio: str | None = None
    followers: int | None = None


@dataclass
class IngestSummary:
    parsed: int = 0
    inserted: int = 0
    updated: int = 0
    conflicts: int = 0
    skipped: int = 0


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_json_export(text: str) -> list[ParsedCandidate]:
    """Parse a JSON array of ``{handle, display_name?, bio?, followers?}``."""
    raw = json.loads(text)
    if not isinstance(raw, list):
        raise ValueError("JSON export must be a top-level array of records.")
    out: list[ParsedCandidate] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        handle = entry.get("handle") or entry.get("screen_name") or entry.get("username")
        if not handle:
            continue
        out.append(
            ParsedCandidate(
                handle=str(handle),
                display_name=(entry.get("display_name") or entry.get("name") or None),
                bio=(entry.get("bio") or entry.get("description") or None),
                followers=_coerce_int(entry.get("followers") or entry.get("followers_count")),
            )
        )
    return out


def parse_html_export(text: str) -> list[ParsedCandidate]:
    """Parse a saved-as-html copy of an X list members page.

    Strategy: find every anchor whose href matches ``/handle`` (single path
    segment, valid Twitter-handle character set, not a route from the denylist).
    Deduplicate by handle. Use the anchor text as display_name when it doesn't
    look like a handle itself.
    """
    from bs4 import BeautifulSoup  # imported lazily — bs4 is a hard dep

    soup = BeautifulSoup(text, "html.parser")
    seen: dict[str, ParsedCandidate] = {}
    for a in soup.find_all("a", href=True):
        href = a.get("href", "")
        m = _HANDLE_PATH_RE.match(href)
        if not m:
            continue
        handle = m.group(1)
        if handle.lower() in _HTML_ROUTE_DENYLIST:
            continue
        # Use the anchor's text as a candidate display name. Anchors whose
        # text starts with '@' are handle renders, not display names.
        # Anchors whose text is the literal handle (same case) are also
        # not display names. Mixed-case forms like "Alice" for handle
        # "alice" ARE preserved because users intentionally pick them.
        text_node = a.get_text(strip=True) or None
        display_name: str | None = None
        if text_node and not text_node.startswith("@") and text_node != handle:
            display_name = text_node
        if handle.lower() in seen:
            existing = seen[handle.lower()]
            if existing.display_name is None and display_name is not None:
                existing.display_name = display_name
        else:
            seen[handle.lower()] = ParsedCandidate(handle=handle, display_name=display_name)
    return list(seen.values())


def _coerce_int(v: object) -> int | None:
    if v is None or v == "":
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _detect_format(path: Path) -> str:
    """Return ``'json'`` or ``'html'``."""
    suffix = path.suffix.lower()
    if suffix == ".json":
        return "json"
    if suffix in {".html", ".htm"}:
        return "html"
    # Fall back to content sniffing.
    head = path.read_text(encoding="utf-8", errors="ignore")[:512].lstrip()
    if head.startswith("[") or head.startswith("{"):
        return "json"
    return "html"


def parse_export(path: str | Path) -> list[ParsedCandidate]:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    fmt = _detect_format(p)
    if fmt == "json":
        return parse_json_export(text)
    return parse_html_export(text)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def run_ingest(export_path: str, *, source_id: str) -> IngestSummary:
    """Parse the export file and upsert each row. Idempotent."""
    parsed = parse_export(export_path)
    summary = IngestSummary(parsed=len(parsed))
    if not parsed:
        return summary
    with open_db() as conn:
        for row in parsed:
            handle = row.handle.strip()
            if not handle or not normalize_handle(handle):
                summary.skipped += 1
                continue
            try:
                res = upsert_candidate(
                    conn,
                    handle=handle,
                    display_name=row.display_name,
                    bio_snapshot=row.bio,
                    followers_snapshot=row.followers,
                    discovery_source=source_id,
                )
            except Exception:
                summary.skipped += 1
                continue
            if res.conflicted:
                summary.conflicts += 1
            elif res.inserted:
                summary.inserted += 1
            elif res.updated:
                summary.updated += 1
    return summary
