"""Operator persona priming for the per-candidate Grok cold-intro draft.

Each Sable operator who runs outreach has a distinct voice register. A
sieggy-flavored cold intro reads differently from an arf-flavored one,
which reads differently from sparta. We bake those differences into the
prompt so Grok's drafted opener matches the operator's actual style
instead of a generic crypto-Twitter register.

This module is the **canonical source of truth** for the operator persona
list. The TS persona union in SableWeb's `kol-create-schemas.ts` is
mirrored from this module via the `sable-kol persona-manifest --json` CLI
verb (see `sable_kol/cli.py`). Tests on both sides of the cross-repo
boundary lockstep against the same fixture so a drift can't silently ship.

`ben` is a placeholder slug. The operator allowlist accepts him today but
no priming text exists for his voice yet. Until the operator supplies
real priming and flips `placeholder=False`, the sidecar and the SableWeb
route both 409-reject any draft request resolved to ben. The block is
deliberately not gated by "fill it out in the UI" — that would itself be
a persona-tuning UI, which is out of scope for v1.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, get_args


PersonaSlug = Literal["sieggy", "sparta", "arf", "ben"]


@dataclass(slots=True, frozen=True)
class PersonaPriming:
    """Per-operator voice priming injected into the Grok cold-intro prompt.

    Each field is a short, declarative sentence that conditions the model
    without becoming the draft itself. Real-priming entries are tuned
    iteratively from operator feedback on real candidate samples; the
    placeholder entry is a hard 409-block until populated.
    """

    voice_register: str
    """One sentence describing how this operator writes — tone, formality, sentence length."""

    opening_style: str
    """One sentence describing how this operator opens a cold DM — what they lead with."""

    avoid: str
    """One sentence describing what this operator never does — register or phrasing to suppress."""

    placeholder: bool = False
    """True for slugs the allowlist accepts but for which priming is not yet authored."""


PERSONAS: dict[PersonaSlug, PersonaPriming] = {
    "sieggy": PersonaPriming(
        voice_register=(
            "Concise, lowercase-leaning, technically literate. Reads like an "
            "engineer who's also a curator — confident but not gratuitously "
            "clever. Sentences run short."
        ),
        opening_style=(
            "Leads with one specific thing the candidate shipped or said, "
            "then a one-line proposition. No greeting. No 'hope you're well'."
        ),
        avoid=(
            "Hype words ('massive', 'huge', 'gm'), exclamation points, "
            "compliments without a referent, and any emoji."
        ),
    ),
    "sparta": PersonaPriming(
        voice_register=(
            "Direct, plain, business-first. A founder talking to another "
            "founder. Sentences are full but punchy."
        ),
        opening_style=(
            "Names the project, names the ask, references one concrete "
            "reason the candidate fits — in that order."
        ),
        avoid=(
            "Crypto-Twitter slang, ironic detachment, and any framing that "
            "sounds like a cold-outreach template."
        ),
    ),
    "arf": PersonaPriming(
        voice_register=(
            "Warm, terminally-online crypto-native. Comfortable with "
            "lowercase, ironic register, and inside references when they "
            "land. Knows when to drop them and write plainly."
        ),
        opening_style=(
            "Opens with a peer-level observation — what's going on in the "
            "candidate's orbit right now — before pivoting to the project."
        ),
        avoid=(
            "Corporate-deck phrasing, formal sign-offs, and any line that "
            "could be auto-generated by a SaaS outreach tool."
        ),
    ),
    "ben": PersonaPriming(
        voice_register="<placeholder — operator must supply>",
        opening_style="<placeholder — operator must supply>",
        avoid="<placeholder — operator must supply>",
        placeholder=True,
    ),
}


def _validate_persona_table() -> None:
    """Sanity-check at import time that PERSONAS matches the PersonaSlug Literal.

    A drift here is a developer error (someone added a slug to the Literal
    but forgot the priming, or vice versa). Catching it on import is far
    less surprising than the schema-validation failure that'd otherwise
    surface mid-request.
    """
    literal_slugs = set(get_args(PersonaSlug))
    table_slugs = set(PERSONAS.keys())
    if literal_slugs != table_slugs:
        missing = literal_slugs - table_slugs
        extra = table_slugs - literal_slugs
        raise RuntimeError(
            f"persona_priming drift: missing in PERSONAS={missing!r}, "
            f"extra in PERSONAS={extra!r}"
        )


_validate_persona_table()


def manifest() -> dict[str, list[str]]:
    """Return the persona manifest as a JSON-serializable dict.

    Used by both the test suite (`tests/test_persona_priming.py`) and the
    `sable-kol persona-manifest --json` CLI. SableWeb's CI reads the
    fixture this CLI emits to lockstep its TypeScript persona union.
    """
    return {
        "slugs": sorted(PERSONAS.keys()),
        "placeholder_slugs": sorted(
            slug for slug, p in PERSONAS.items() if p.placeholder
        ),
    }


def is_placeholder(slug: PersonaSlug) -> bool:
    """Convenience for callers that want to short-circuit before the sidecar."""
    return PERSONAS[slug].placeholder


def priming_for(slug: PersonaSlug) -> PersonaPriming:
    """Look up priming for a slug. Caller is expected to have validated the slug."""
    return PERSONAS[slug]


__all__ = [
    "PERSONAS",
    "PersonaPriming",
    "PersonaSlug",
    "is_placeholder",
    "manifest",
    "priming_for",
]
