"""Produce a tiered outreach plan deliverable for a Sable client.

Driven by ``~/.sable/clients/<id>.yaml`` (or production
``/opt/sable/clients/<id>.yaml``). All client-specific knobs live in
that config — themes for vibe-fit, sector_focus, audience handles,
manual pins, denylist extras, network axes, tier thresholds.

For each run, writes BOTH a filtered (default) and an unfiltered
``_full`` variant. SableWeb's API serves the filtered file from cache
when query params don't override; loads the ``_full`` file and
re-applies the filter the operator did NOT request to disable
otherwise (audit P1-2).

Tiering modes:
  * **stealth** (default for SolStitch): inverted reach. Tier-A is
    sub-15K micro-influencers with high in-pool penetration OR high
    vibe-fit.
  * **public**: classic reach-descending tiers.

Filters (always applied; ``--include-orgs`` and ``--include-celebs`` override):
  * `is_organization` from `sable_kol.filters`
  * `is_celebrity` — Vitalik / CZ / Elon / Saylor class

Tags are NOT baked into the deliverables (audit #2). SableWeb merges
live tag state from Postgres at request time before streaming downloads.

Usage:
    .venv/bin/python scripts/build_outreach_plan.py --client solstitch
        [--mode stealth|public]
        [--output-dir PATH]
        [--include-orgs]                # write only the _full variant
        [--include-celebs]              # write only the _full variant
        [--top-k 250]
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
from datetime import date
from pathlib import Path

from sable_kol.client_config import ClientConfig, load_client_config, outreach_output_dir
from sable_kol.db import open_db
from sable_kol.filters import is_organization, is_celebrity, PERSON_ALLOWLIST
from sable_kol.follow_graph import (
    Cluster,
    build_co_follow_matrix,
    cluster_kols,
    cluster_label_via_tfidf,
)
from sable_kol.outreach_plan import build_plan, to_csv_rows, to_json_payload


CLUSTER_THRESHOLD = 0.05


def load_candidates_sector_filtered(conn, sector_focus: list[str], top_k: int):
    """Pull live + classified rows whose sector_tags intersect ``sector_focus``.

    Sector focus comes from the per-client config — what's "fashion+culture+art"
    for SolStitch may be "infra+gaming" for TIG. Hardcoded SQL LIKE patterns
    are gone; we OR-join over the client's configured set.
    """
    if not sector_focus:
        # No sector filter — let everything through; downstream tiering filters.
        sector_clause = "1=1"
        params: dict = {"k": top_k}
    else:
        # Build OR-joined LIKE clauses with named bindings.
        likes = []
        params = {"k": top_k}
        for i, sec in enumerate(sector_focus):
            key = f"sec{i}"
            likes.append(f"sector_tags_json LIKE :{key}")
            params[key] = f"%{sec}%"
        sector_clause = "(" + " OR ".join(likes) + ")"
    sql = f"""
      SELECT * FROM kol_candidates
      WHERE is_unresolved = 0
        AND status = 'active'
        AND archetype_tags_json != '[]'
        AND {sector_clause}
      ORDER BY (kol_strength_score IS NULL), kol_strength_score DESC,
               followers_snapshot DESC NULLS LAST
      LIMIT :k
    """
    from sable_kol.db import _row_to_candidate
    rows = conn.execute(sql, params).fetchall()
    return [_row_to_candidate(r) for r in rows]


def render_markdown(payload: dict, kingmakers: list[dict]) -> str:
    summary = payload["summary"]
    meta = payload.get("meta") or {}
    mode = meta.get("mode", "stealth")
    lines: list[str] = []
    lines.append("# SolStitch outreach plan — 2026-05-07\n")
    lines.append(f"**Mode:** `{mode}` "
                 f"({'pre-launch — sub-15K hidden gems with high in-pool penetration' if mode == 'stealth' else 'post-launch — reach-descending'})\n")
    lines.append("Generated by `scripts/build_outreach_plan.py` from the post–Phase-6b bank state.\n")
    lines.append("**Source mix:** Doji + 9dcc + Fabricant audience extraction (Phase 2) + ")
    lines.append("existing bank (Cahit, FWB, cool_ct, etc.). Filtered to ")
    lines.append("sector ∈ {fashion, culture, art, design, nfts, streetwear, creator, media, social}.\n")
    lines.append("**Filters applied:**")
    if not meta.get("include_orgs", False):
        lines.append("  * `is_organization` — orgs (brands, marketplaces, protocols) DROPPED. "
                     "Outreach to humans behind them, not the brand handles.")
    if not meta.get("include_celebs", False):
        lines.append("  * `is_celebrity` — Vitalik / CZ / Elon / Saylor / etc. DROPPED. "
                     "These broadcast accounts won't shill a stealth project.")
    fdrop = meta.get("filtered_count", 0)
    by_reason = meta.get("filtered_by_reason", {})
    if fdrop:
        lines.append(f"  * **{fdrop} candidates filtered total** "
                     f"({', '.join(f'{n} {r}' for r, n in by_reason.items())})\n")
    lines.append("---\n")

    lines.append("## Summary\n")
    lines.append(f"* **Total candidates:** {summary['total']}")
    if mode == "stealth":
        lines.append(f"* **Tier A (sub-15K hidden gems, in_pool ≥6, vibe ≥0.5):** {summary['tier_A']}")
        lines.append(f"* **Tier B (15K-50K mid-reach, vibe ≥0.4):** {summary['tier_B']}")
        lines.append(f"* **Tier C (templated, vibe ≥0.3):** {summary['tier_C']}")
    else:
        lines.append(f"* **Tier A (high-touch, ≥100K reach):** {summary['tier_A']}")
        lines.append(f"* **Tier B (warm-DM, 10K-100K reach):** {summary['tier_B']}")
        lines.append(f"* **Tier C (templated, 1K-10K reach):** {summary['tier_C']}")
    lines.append(f"* **Below threshold (informational):** {summary['unranked']}\n")

    if mode == "stealth":
        lines.append("## Why stealth-mode tiering inverts the reach pyramid\n")
        lines.append("Pre-launch projects without a story to amplify need **early-adopter")
        lines.append("micro-influencers**, not mega-broadcasters. The accounts you want are:")
        lines.append("  * sub-15K-follower curators / artists / designers / connectors")
        lines.append("  * with high penetration into the **bigger** KOLs' following graphs")
        lines.append("  * who actually engage with DMs from new projects")
        lines.append("  * and whose taste matches SolStitch's mission")
        lines.append("Tier-A is therefore the **hidden gems** — when these people post,")
        lines.append("the next layer of larger accounts notices. Mid- and large-reach")
        lines.append("accounts are demoted to Tier-B/C: useful when there's traction to")
        lines.append("amplify, less useful before the debut. Switch to `--mode public`")
        lines.append("post-launch to revert to reach-descending tiers.\n")

    lines.append("## Caveat — read before using\n")
    lines.append("* `social_proximity_brokers` is the **co-follow-on-X** signal — KOLs in our")
    lines.append("  variant-2 cohort who follow the target. **This does NOT imply willingness")
    lines.append("  to make an introduction.** Use as a prior, not a commitment. Operator-")
    lines.append("  confirmed intros go in the separate `operator_confirmed_intros` field,")
    lines.append("  populated via manual annotation.")
    lines.append("* Reach uses `max(X, Instagram, TikTok, YouTube, Threads)`. Most rows are")
    lines.append("  X-only (no IG/TikTok data) — those tiers may be biased downward. Phase 4.5")
    lines.append("  cross-platform enrichment is conditional and not yet run.")
    lines.append("* Cluster IDs / labels come from Jaccard threshold 0.05 over the variant-2")
    lines.append("  cohort's followings. Most clusters are singletons; the cohort has")
    lines.append("  heterogeneous taste, so cluster-tailored messaging is low-leverage.\n")

    lines.append("## Kingmakers — standing high-leverage targets\n")
    lines.append("Accounts followed by ≥8 of the variant-2 cohort. These are the highest-")
    lines.append("leverage standing follow-targets across the SolStitch-adjacent KOL ecosystem.\n")
    lines.append("| handle | followed by N of 50 cohort KOLs |")
    lines.append("|--------|--------------------------------:|")
    for k in kingmakers[:30]:
        lines.append(f"| `@{k['handle']}` | {k['follower_count_in_pool']} |")
    lines.append("")

    for tier in ("A", "B", "C"):
        rows = payload["targets"].get(tier, [])
        if not rows:
            continue
        lines.append(f"## Tier {tier} ({len(rows)} candidates)\n")
        if tier == "A":
            cadence = "1-3 personalized DMs/day; bespoke threads"
        elif tier == "B":
            cadence = "5-10 DMs/day with cluster-specific opening; 6-12 days to clear"
        else:
            cadence = "10-15 templated DMs/day; 11-16 days to clear (CSV export below)"
        lines.append(f"_Cadence: {cadence}_\n")

        if tier == "A":
            for r in rows:
                lines.append(f"### `@{r['handle']}`")
                lines.append(f"* **Reach:** {r['reach_total']:,} ({r['primary_platform']}-primary)")
                if r.get('archetype'):
                    lines.append(f"* **Archetype:** {r['archetype']}")
                if r.get('cluster_id') is not None:
                    lines.append(f"* **Cluster:** {r['cluster_id']} — {r.get('cluster_label') or '(unlabeled)'}")
                if r.get('manual_pin'):
                    lines.append(f"* **Manual pin:** True (operator-validated must-have)")
                if r.get('social_proximity_brokers'):
                    lines.append(f"* **Social-proximity brokers (co-follow only, NOT intro paths):** "
                                 f"{', '.join('@' + h for h in r['social_proximity_brokers'])}")
                lines.append(f"* **Operator-confirmed intros:** _(blank — operator annotates manually)_")
                if r.get('sources'):
                    lines.append(f"* **Discovery sources:** {', '.join(r['sources'][:6])}")
                lines.append(f"* **Score:** {r['score']:.2f}")
                lines.append("")
        else:
            lines.append("| handle | reach | platform | cluster | archetype | brokers | sources |")
            lines.append("|--------|------:|:--------:|--------:|-----------|---------|---------|")
            for r in rows[:50]:  # cap inline; full list in JSON/CSV
                brokers = ", ".join(f"@{h}" for h in r.get('social_proximity_brokers', [])[:3])
                src_joined = ", ".join((r.get('sources') or [])[:2])
                cid = r.get('cluster_id') if r.get('cluster_id') is not None else ""
                lines.append(
                    f"| `@{r['handle']}` | {r['reach_total']:,} | {r['primary_platform']} | "
                    f"{cid} | {r.get('archetype', '')} | {brokers} | {src_joined} |"
                )
            if len(rows) > 50:
                lines.append(f"\n_({len(rows) - 50} additional rows in JSON/CSV)_\n")
            else:
                lines.append("")

    lines.append("## Measurement protocol\n")
    lines.append("Per the SolStitch outreach plan v3 §8.4. Operator should set up a")
    lines.append("tracking sheet (Google Sheet) with columns:")
    lines.append("`handle | tier | cluster | send_date | opened | replied | reply_sentiment | follow_back | follow_up_action`\n")
    lines.append("**Conversion definitions:**")
    lines.append("* **Reply** — any non-bot response within 7 days")
    lines.append("* **Engaged reply** — reply that asks a question or expresses interest")
    lines.append("* **Conversion** — scheduled call OR follows SolStitch X account OR engages with debut content\n")
    lines.append("**Reviews:** 7-day per-tier reply rate (iterate templates if cluster reply rate <5%); ")
    lines.append("30-day per-tier conversion rate (drives X Ads decision per §8.5).\n")

    lines.append("## X Ads decision matrix\n")
    lines.append("After 30-day measurement window:")
    lines.append("| 30-day Tier-B engaged-reply rate | Action |")
    lines.append("|---:|---|")
    lines.append("| ≥10% | $500 promoted-post test against Tier-B+C audience CSV |")
    lines.append("| 5-10% | $200 micro-test; iterate creative on top-cluster |")
    lines.append("| <5% | Don't scale; refine segmentation/messaging first |\n")

    lines.append("**X Ads tailored audience prep:** the CSV export below has all 200 handles. ")
    lines.append("Per `docs.x.com/x-ads-api/audiences`, 200 likely meets API targeting min (100) ")
    lines.append("but NOT UI targeting min (500). If operator wants UI-managed campaigns, expand ")
    lines.append("by combining with `cool_ct` + `fwb_tweets` curator-list members → 600+ handles.\n")

    return "\n".join(lines) + "\n"


def vibe_fit_score(candidate, themes: list[str]) -> float:
    """Cheap theme-keyword overlap score in [0, 1].

    Tokenize bio + display_name into lowercase word-prefixes; count matches
    against the themes list (themes themselves split into words first).
    Score = unique_matches / max_possible. Bounded at 1.0.

    Phase 3 of the generalization plan replaces this with embeddings.
    """
    if not themes:
        return 0.0
    text = ((candidate.bio_snapshot or "") + " " + (candidate.display_name or "")).lower()
    words = set(re.findall(r"[a-z][a-z0-9_-]{2,}", text))
    theme_tokens: set[str] = set()
    for t in themes:
        for w in re.findall(r"[a-z][a-z0-9_-]{2,}", t.lower()):
            theme_tokens.add(w)
    if not theme_tokens:
        return 0.0
    matches = words & theme_tokens
    # Cap at 1.0 — saturate at 6+ matches.
    return min(1.0, len(matches) / 6.0)


def filter_candidates(candidates, *, include_orgs: bool, include_celebs: bool):
    """Apply org + celebrity filters and return (kept, dropped_with_reasons)."""
    kept = []
    dropped: list[tuple[str, str]] = []
    for c in candidates:
        archetypes = list(c.archetype_tags or [])
        bio = c.bio_snapshot
        h = c.handle_normalized
        if not include_orgs and is_organization(h, archetypes, bio):
            dropped.append((h, "organization"))
            continue
        if not include_celebs and is_celebrity(h, c.followers_snapshot, c.following_count):
            dropped.append((h, "celebrity"))
            continue
        kept.append(c)
    return kept, dropped


def stealth_tier(target, vibe: float, manual_pin: bool, thresholds) -> str:
    """Stealth-mode tier assignment driven by client config.

    Per /grill-me Q-stealth + audit: Tier-A is sub-reach-cap micro-influencers
    where EITHER vibe-fit OR broker count clears their respective floor.
    Manual pins always Tier-A.

    `thresholds` is a `TierThresholds` dataclass from `client_config`.
    Each tier dataclass exposes optional `max_followers`, `min_followers`,
    `min_brokers`, `min_vibe`. Missing fields are treated as "no constraint".
    """
    if manual_pin:
        return "A"
    f = target.reach_total
    brokers = len(target.social_proximity_brokers)

    def _passes(tier) -> bool:
        if tier.max_followers is not None and f > tier.max_followers:
            return False
        if tier.min_followers is not None and f < tier.min_followers:
            return False
        # min_brokers OR min_vibe — either clears the bar
        gate_brokers = tier.min_brokers is not None and brokers >= tier.min_brokers
        gate_vibe = tier.min_vibe is not None and vibe >= tier.min_vibe
        if (tier.min_brokers is not None) or (tier.min_vibe is not None):
            return gate_brokers or gate_vibe
        return True

    if _passes(thresholds.A):
        return "A"
    if _passes(thresholds.B):
        return "B"
    if _passes(thresholds.C):
        return "C"
    return "unranked"


def public_tier(target, manual_pin: bool, thresholds) -> str:
    """Public-mode tier — classic reach-descending.

    Tier-A: followers >= thresholds.A.min_followers
    Tier-B: followers >= thresholds.B.min_followers
    Tier-C: followers >= thresholds.C.min_followers
    Below all → unranked.
    Manual pins always Tier-A.
    """
    if manual_pin:
        return "A"
    f = target.reach_total
    if thresholds.A.min_followers is not None and f >= thresholds.A.min_followers:
        return "A"
    if thresholds.B.min_followers is not None and f >= thresholds.B.min_followers:
        return "B"
    if thresholds.C.min_followers is not None and f >= thresholds.C.min_followers:
        return "C"
    return "unranked"


def _generate_run(
    conn,
    *,
    config: ClientConfig,
    mode: str,
    top_k: int,
    include_orgs: bool,
    include_celebs: bool,
    kings,
    co_follow_matrix,
    clusters,
):
    """One pass: filter, vibe-score, tier, build payload + serializations.

    Returns ``(payload_dict, csv_rows, kingmakers_payload)`` ready to write.
    Splitting this out so we can call it twice — once for the filtered
    output, once for the ``_full`` variant.
    """
    # 1. Load sector-filtered candidates from the bank.
    raw_candidates = load_candidates_sector_filtered(
        conn, sector_focus=config.sector_focus, top_k=top_k * 2
    )

    # 2. Apply org + celebrity filters BEFORE ranking (configurable).
    candidates, dropped = filter_candidates(
        raw_candidates,
        include_orgs=include_orgs,
        include_celebs=include_celebs,
    )
    candidates = candidates[:top_k]

    # 3. Compute vibe-fit per candidate (themes from config).
    manual_pin_set = {h.lower() for h in config.manual_pins}
    vibe_by_handle: dict[str, float] = {}
    for c in candidates:
        vibe_by_handle[c.handle_normalized] = vibe_fit_score(c, config.themes)

    # 4. Build the plan via outreach_plan.build_plan, then re-tier per mode.
    targets = build_plan(
        conn,
        candidates=candidates,
        top_k=top_k,
        co_follow_matrix=co_follow_matrix,
        clusters=clusters,
        manual_pins=manual_pin_set,
    )

    thresholds = config.tier_thresholds[mode]
    for t in targets:
        vibe = vibe_by_handle.get(t.handle, 0.0)
        pin = t.handle in manual_pin_set
        if mode == "stealth":
            t.tier = stealth_tier(t, vibe, pin, thresholds)
        else:
            t.tier = public_tier(t, pin, thresholds)
        t.suggested_theme = (
            f"vibe={vibe:.2f}" if not t.suggested_theme else t.suggested_theme
        )

    # Sort within tier: brokers desc, vibe desc, reach asc (small first).
    tier_rank = {"A": 0, "B": 1, "C": 2, "unranked": 3}
    targets.sort(key=lambda t: (
        tier_rank.get(t.tier, 99),
        -len(t.social_proximity_brokers),
        -vibe_by_handle.get(t.handle, 0.0),
        t.reach_total,
    ))

    # Annotate each target with is_org / is_celeb so SableWeb can re-filter
    # the _full variant per query params (Codex P1-2 — partial flag handling).
    # The original raw_candidates list still has all archetypes / following_count.
    by_handle = {c.handle_normalized: c for c in raw_candidates}
    for t in targets:
        c = by_handle.get(t.handle)
        if c is None:
            t_is_org = False
            t_is_celeb = False
        else:
            archetypes = list(c.archetype_tags or [])
            t_is_org = is_organization(t.handle, archetypes, c.bio_snapshot)
            t_is_celeb = is_celebrity(t.handle, c.followers_snapshot, c.following_count)
        # Stash on the dataclass via __dict__ (slots=False on OutreachTarget
        # so this is fine). asdict() will pick them up in to_json_payload.
        t.__dict__["is_org"] = t_is_org  # type: ignore[index]
        t.__dict__["is_celeb"] = t_is_celeb  # type: ignore[index]

    payload = to_json_payload(targets)
    # to_json_payload uses asdict() which doesn't include __dict__ extras —
    # walk the payload and re-inject the booleans.
    for tier_key in ("A", "B", "C", "unranked"):
        rows = payload["targets"].get(tier_key, [])
        for row in rows:
            t = next((tt for tt in targets if tt.handle == row["handle"]), None)
            if t is not None:
                row["is_org"] = bool(t.__dict__.get("is_org", False))
                row["is_celeb"] = bool(t.__dict__.get("is_celeb", False))

    by_reason: dict[str, int] = {}
    for _h, r in dropped:
        by_reason[r] = by_reason.get(r, 0) + 1
    payload["meta"] = {
        "schema_version": 1,
        "client_id": config.client_id,
        "client_display_name": config.display_name,
        "mode": mode,
        "include_orgs": include_orgs,
        "include_celebs": include_celebs,
        "filtered_count": len(dropped),
        "filtered_by_reason": by_reason,
        "themes": config.themes,
        "network_axes": {
            "x": {"label": config.network_axes.x.label},
            "y": {"label": config.network_axes.y.label},
        },
    }

    kingmakers_payload = [
        {"handle": k.handle, "follower_count_in_pool": k.follower_count_in_pool}
        for k in kings
    ]
    csv_rows = to_csv_rows(targets)
    # Mirror is_org / is_celeb onto CSV rows so downstream tools (Hubspot
    # etc) can filter on them.
    for row in csv_rows:
        t = next((tt for tt in targets if tt.handle == row["handle"]), None)
        if t is not None:
            row["is_org"] = "1" if t.__dict__.get("is_org") else "0"
            row["is_celeb"] = "1" if t.__dict__.get("is_celeb") else "0"
    return payload, csv_rows, kingmakers_payload


def _write_variant(
    out_dir: Path,
    *,
    client_id: str,
    mode: str,
    date_slug: str,
    is_full: bool,
    payload: dict,
    csv_rows: list[dict],
    kingmakers_payload,
) -> dict[str, Path]:
    """Write the four artifacts (.md, .json, .csv plus leads.{json,csv}) for
    one variant. Returns ``{file_kind: path}`` mapping for symlink updates.

    Filename pattern (Codex P1-1 + audit #6):
        {client}_{doc}_{date}_{mode}[_full].{ext}
    where doc ∈ {report, leads}.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    full_suffix = "_full" if is_full else ""
    base = f"{client_id}_{{doc}}_{date_slug}_{mode}{full_suffix}.{{ext}}"

    paths: dict[str, Path] = {}

    # report.json
    paths["report.json"] = out_dir / base.format(doc="report", ext="json")
    paths["report.json"].write_text(json.dumps(payload, indent=2), encoding="utf-8")

    # report.md (human-facing)
    paths["report.md"] = out_dir / base.format(doc="report", ext="md")
    paths["report.md"].write_text(
        render_markdown(payload, kingmakers_payload), encoding="utf-8"
    )

    # leads.json (flat array — every visible target as one row)
    leads = []
    for tier in ("A", "B", "C", "unranked"):
        for t in payload["targets"].get(tier, []):
            leads.append(t)
    leads_payload = {
        "_meta": payload["meta"],
        "leads": leads,
    }
    paths["leads.json"] = out_dir / base.format(doc="leads", ext="json")
    paths["leads.json"].write_text(json.dumps(leads_payload, indent=2), encoding="utf-8")

    # leads.csv
    paths["leads.csv"] = out_dir / base.format(doc="leads", ext="csv")
    if csv_rows:
        with open(paths["leads.csv"], "w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(csv_rows[0].keys()))
            writer.writeheader()
            writer.writerows(csv_rows)
    else:
        paths["leads.csv"].write_text("", encoding="utf-8")

    return paths


def _update_symlink(target: Path, link_path: Path) -> None:
    """Replace ``link_path`` with a symlink → ``target``. Uses relative path
    so /opt/sable/outreach mounts from container side still resolve."""
    try:
        if link_path.is_symlink() or link_path.exists():
            link_path.unlink()
    except OSError:
        pass
    rel = os.path.relpath(target, link_path.parent)
    try:
        link_path.symlink_to(rel)
    except OSError as exc:
        # macOS APFS can fail for cross-volume; fall back to copy.
        print(f"  warning: symlink {link_path.name} → {rel} failed ({exc}); copying instead")
        link_path.write_bytes(Path(target).read_bytes())


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--client", required=True,
                    help="Client id (matches a YAML at ~/.sable/clients/<id>.yaml).")
    ap.add_argument("--mode", choices=["stealth", "public"], default=None,
                    help="Tiering mode. Defaults to the client's configured mode.")
    ap.add_argument("--output-dir", default=None,
                    help="Override output directory (default: per-client config-driven path).")
    ap.add_argument("--top-k", type=int, default=250,
                    help="Top-K candidates from the bank before filtering. Default 250.")
    ap.add_argument("--include-orgs", action="store_true",
                    help="When set, the FILTERED variant also includes orgs. The _full variant always does.")
    ap.add_argument("--include-celebs", action="store_true",
                    help="When set, the FILTERED variant also includes celebrities. The _full variant always does.")
    args = ap.parse_args()

    config = load_client_config(args.client)
    mode = args.mode or config.mode
    if mode not in ("stealth", "public"):
        raise ValueError(f"unsupported mode {mode!r}")

    out_dir = Path(args.output_dir) if args.output_dir else outreach_output_dir(args.client)
    date_slug = date.today().isoformat()

    print(f"client: {config.client_id} ({config.display_name}) · mode: {mode}")
    print(f"output dir: {out_dir}")

    with open_db() as conn:
        # Build co-follow matrix + kingmakers ONCE (mode-independent).
        m = build_co_follow_matrix(conn, extract_type="following")
        print(f"co-follow matrix: rows={len(m.rows)} cols={len(m.cols)} nnz={m.nnz}")
        clusters_at = cluster_kols(m, thresholds=(CLUSTER_THRESHOLD,))
        clusters: list[Cluster] = clusters_at[CLUSTER_THRESHOLD]
        for c in clusters:
            c.label = cluster_label_via_tfidf(c.members, m, top_k=4)
        from sable_kol.follow_graph import identify_kingmakers
        kings = identify_kingmakers(m, min_count=8)
        print(f"kingmakers (>=8 cohort): {len(kings)}")

        # Filtered variant (default): orgs+celebs dropped.
        # Full variant (always written): nothing dropped.
        # The CLI flags `--include-orgs / --include-celebs` only affect the
        # FILTERED variant on disk, so operators running locally can produce
        # a custom filtered file. SableWeb's API uses the _full file
        # post-processing per Codex P1-2.
        print("\n--- filtered variant ---")
        f_payload, f_rows, f_kings = _generate_run(
            conn, config=config, mode=mode, top_k=args.top_k,
            include_orgs=args.include_orgs, include_celebs=args.include_celebs,
            kings=kings, co_follow_matrix=m, clusters=clusters,
        )
        f_paths = _write_variant(
            out_dir, client_id=config.client_id, mode=mode, date_slug=date_slug,
            is_full=False, payload=f_payload, csv_rows=f_rows,
            kingmakers_payload=f_kings,
        )
        for kind, p in f_paths.items():
            print(f"  wrote {p.name}")

        print("\n--- _full variant (orgs + celebs included) ---")
        full_payload, full_rows, full_kings = _generate_run(
            conn, config=config, mode=mode, top_k=args.top_k,
            include_orgs=True, include_celebs=True,
            kings=kings, co_follow_matrix=m, clusters=clusters,
        )
        full_paths = _write_variant(
            out_dir, client_id=config.client_id, mode=mode, date_slug=date_slug,
            is_full=True, payload=full_payload, csv_rows=full_rows,
            kingmakers_payload=full_kings,
        )
        for kind, p in full_paths.items():
            print(f"  wrote {p.name}")

        # Update latest_<mode>_<doc>.<ext> symlinks (point to filtered variant).
        # The _full variant gets latest_<mode>_<doc>_full.<ext> symlinks.
        for kind in ("report.json", "report.md", "leads.json", "leads.csv"):
            doc, ext = kind.split(".")
            link_filtered = out_dir / f"latest_{mode}_{doc}.{ext}"
            link_full = out_dir / f"latest_{mode}_{doc}_full.{ext}"
            _update_symlink(f_paths[kind], link_filtered)
            _update_symlink(full_paths[kind], link_full)

        print("\n=== summary ===")
        print(json.dumps(f_payload["summary"], indent=2))


if __name__ == "__main__":
    main()
